"""create catalog tables

Revision ID: 7aec4b4c1b96
Revises: 
Create Date: 2026-08-25 18:26:58.055105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aec4b4c1b96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dux_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_dux_id'), 'categorias', ['dux_id'], unique=True)
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_index(op.f('ix_categorias_nombre'), 'categorias', ['nombre'], unique=True)
    op.create_index(op.f('ix_categorias_slug'), 'categorias', ['slug'], unique=True)
    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dux_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marcas_dux_id'), 'marcas', ['dux_id'], unique=True)
    op.create_index(op.f('ix_marcas_id'), 'marcas', ['id'], unique=False)
    op.create_index(op.f('ix_marcas_nombre'), 'marcas', ['nombre'], unique=True)
    op.create_index(op.f('ix_marcas_slug'), 'marcas', ['slug'], unique=True)
    op.create_table('subcategorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dux_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcategorias_categoria_id'), 'subcategorias', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_subcategorias_dux_id'), 'subcategorias', ['dux_id'], unique=True)
    op.create_index(op.f('ix_subcategorias_id'), 'subcategorias', ['id'], unique=False)
    op.create_index(op.f('ix_subcategorias_nombre'), 'subcategorias', ['nombre'], unique=False)
    op.create_index(op.f('ix_subcategorias_slug'), 'subcategorias', ['slug'], unique=True)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dux_codigo', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('codigo_externo', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('costo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('porcentaje_iva', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('cantidad_unidades_por_bulto', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('habilitado', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('fecha_creacion_dux', sa.Date(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('subcategoria_id', sa.Integer(), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategoria_id'], ['subcategorias.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_categoria_id'), 'productos', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_productos_dux_codigo'), 'productos', ['dux_codigo'], unique=True)
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_index(op.f('ix_productos_marca_id'), 'productos', ['marca_id'], unique=False)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.create_index(op.f('ix_productos_slug'), 'productos', ['slug'], unique=True)
    op.create_index(op.f('ix_productos_subcategoria_id'), 'productos', ['subcategoria_id'], unique=False)
    op.create_table('codigos_barra_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'codigo', name='uq_producto_codigo_barra')
    )
    op.create_index(op.f('ix_codigos_barra_productos_codigo'), 'codigos_barra_productos', ['codigo'], unique=False)
    op.create_index(op.f('ix_codigos_barra_productos_id'), 'codigos_barra_productos', ['id'], unique=False)
    op.create_index(op.f('ix_codigos_barra_productos_producto_id'), 'codigos_barra_productos', ['producto_id'], unique=False)
    op.create_table('imagenes_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('orden', sa.Integer(), server_default='0', nullable=False),
    sa.Column('principal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imagenes_productos_id'), 'imagenes_productos', ['id'], unique=False)
    op.create_index(op.f('ix_imagenes_productos_producto_id'), 'imagenes_productos', ['producto_id'], unique=False)
    op.create_table('precios_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('dux_id_lista', sa.Integer(), nullable=False),
    sa.Column('nombre_lista', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'dux_id_lista', name='uq_precio_producto_lista')
    )
    op.create_index(op.f('ix_precios_productos_dux_id_lista'), 'precios_productos', ['dux_id_lista'], unique=False)
    op.create_index(op.f('ix_precios_productos_id'), 'precios_productos', ['id'], unique=False)
    op.create_index(op.f('ix_precios_productos_nombre_lista'), 'precios_productos', ['nombre_lista'], unique=False)
    op.create_index(op.f('ix_precios_productos_producto_id'), 'precios_productos', ['producto_id'], unique=False)
    op.create_table('stocks_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('dux_id_deposito', sa.Integer(), nullable=False),
    sa.Column('nombre_deposito', sa.String(length=100), nullable=False),
    sa.Column('stock_real', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('stock_reservado', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('stock_disponible', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('dux_id_det_item', sa.Integer(), nullable=True),
    sa.Column('codigo_barra_detalle', sa.String(length=100), nullable=True),
    sa.Column('talle', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'dux_id_deposito', 'dux_id_det_item', name='uq_stock_producto_deposito_detalle')
    )
    op.create_index(op.f('ix_stocks_productos_color'), 'stocks_productos', ['color'], unique=False)
    op.create_index(op.f('ix_stocks_productos_dux_id_deposito'), 'stocks_productos', ['dux_id_deposito'], unique=False)
    op.create_index(op.f('ix_stocks_productos_dux_id_det_item'), 'stocks_productos', ['dux_id_det_item'], unique=False)
    op.create_index(op.f('ix_stocks_productos_id'), 'stocks_productos', ['id'], unique=False)
    op.create_index(op.f('ix_stocks_productos_producto_id'), 'stocks_productos', ['producto_id'], unique=False)
    op.create_index(op.f('ix_stocks_productos_talle'), 'stocks_productos', ['talle'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_productos_talle'), table_name='stocks_productos')
    op.drop_index(op.f('ix_stocks_productos_producto_id'), table_name='stocks_productos')
    op.drop_index(op.f('ix_stocks_productos_id'), table_name='stocks_productos')
    op.drop_index(op.f('ix_stocks_productos_dux_id_det_item'), table_name='stocks_productos')
    op.drop_index(op.f('ix_stocks_productos_dux_id_deposito'), table_name='stocks_productos')
    op.drop_index(op.f('ix_stocks_productos_color'), table_name='stocks_productos')
    op.drop_table('stocks_productos')
    op.drop_index(op.f('ix_precios_productos_producto_id'), table_name='precios_productos')
    op.drop_index(op.f('ix_precios_productos_nombre_lista'), table_name='precios_productos')
    op.drop_index(op.f('ix_precios_productos_id'), table_name='precios_productos')
    op.drop_index(op.f('ix_precios_productos_dux_id_lista'), table_name='precios_productos')
    op.drop_table('precios_productos')
    op.drop_index(op.f('ix_imagenes_productos_producto_id'), table_name='imagenes_productos')
    op.drop_index(op.f('ix_imagenes_productos_id'), table_name='imagenes_productos')
    op.drop_table('imagenes_productos')
    op.drop_index(op.f('ix_codigos_barra_productos_producto_id'), table_name='codigos_barra_productos')
    op.drop_index(op.f('ix_codigos_barra_productos_id'), table_name='codigos_barra_productos')
    op.drop_index(op.f('ix_codigos_barra_productos_codigo'), table_name='codigos_barra_productos')
    op.drop_table('codigos_barra_productos')
    op.drop_index(op.f('ix_productos_subcategoria_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_slug'), table_name='productos')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_index(op.f('ix_productos_marca_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_dux_codigo'), table_name='productos')
    op.drop_index(op.f('ix_productos_categoria_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_subcategorias_slug'), table_name='subcategorias')
    op.drop_index(op.f('ix_subcategorias_nombre'), table_name='subcategorias')
    op.drop_index(op.f('ix_subcategorias_id'), table_name='subcategorias')
    op.drop_index(op.f('ix_subcategorias_dux_id'), table_name='subcategorias')
    op.drop_index(op.f('ix_subcategorias_categoria_id'), table_name='subcategorias')
    op.drop_table('subcategorias')
    op.drop_index(op.f('ix_marcas_slug'), table_name='marcas')
    op.drop_index(op.f('ix_marcas_nombre'), table_name='marcas')
    op.drop_index(op.f('ix_marcas_id'), table_name='marcas')
    op.drop_index(op.f('ix_marcas_dux_id'), table_name='marcas')
    op.drop_table('marcas')
    op.drop_index(op.f('ix_categorias_slug'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_nombre'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_dux_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
